package Administrator.Algorithm;

public class Linear {
	
	/** The settings. */
	private Settings settings;
	
	/**
	 * Instantiates a new harmonic oscillator.
	 */
	public Linear(){
		this.settings = Settings.getSettings();
	}
	
//	public float dynamicLinearFirst(float y){
//		return y;
//	}
	
	/**
	 * Mathematical law of harmonic oscillator.
	 *
	 * @param x  virtual player's position
	 * @param y  virtual player's velocity
	 * @param u  control signal generated by the controller
	 * @return the virtual player's accelerator. This value of acceleration
	 * will be used to evaluated the next value of virtual player's velocity
	 * and so its position (nextVel = currentVel + accel*time; nextPos = 
	 * currentPos + vel*time)
	 */
	public float dynamicLinearSecond(int index, float x, float y, float u){
		return (float)(-settings.getA(index)*y - settings.getB(index)*x + u);
	}
}
